### ISSUE TITLE
Inventory Widget Design Decission

### ISSUE THREAD

**Issue by austin-berry** [EniariGames/StaticShock#13]
Alright team, we need to make a design decision for the player inventory widget. I'm not talking graphics or art yet, just the basic layout of it all.

A few examples that everyone should have a good idea of is Skyrim, Fallout | Minecraft, Terraria | Open World Games such as Player Unknown Battlegrounds.

Skyrim and Fallout use more of a text base scroll box on the left and imagery on the right side of the screen.

Minecraft and Terraria use a bottom bar with square icons that can be dragged and dropped or used.

Some open world games use a grid system where it is like a combination of the two above examples. There is usually a grid based panel in which items can be dragged and dropped or used; this shows in a better style for many items.

This is for discussion and I'm looking for a unanimous decision so that I can finish the development for the inventory system player widget.

Looking forward to everyone's responses.

**Comment by austin-berry** [comment]
I personally prefer the **_Skyrim_** feel of it all. I like having a list of item's names that I can quickly scroll through and find what I'm looking for with the number included by the item name itself. When you click on the object, the 3d render of the object is shown on the right hand side along with the items description, weight, etc. What do you guys think?
![tesv-skyrim](https://user-images.githubusercontent.com/35203435/35259022-15f75146-ffb8-11e7-8fbd-a890881b8f13.jpg)

**Comment by Dud10982** [comment]
So i also would rather have the skyrim type inventory system, but the base system was very problematic. It was clunky and had lots of unused space. There was a mod created for the UI called SkyUI that really expanded on how your inventory was layed out. It gave a lot more freedom and simplified how you moved around the menus. It also created icons based on the type of item to catch someones eye quicker. A very similar mod for Fallout 4 was Def_UI. It gives more of a database feel to it rather than a flat one menu to the next, (weapons to types of weapons to weapon rarity) then go all the way back to get to the armor menu etc.
![image](https://user-images.githubusercontent.com/35204357/35292856-acd38da0-0026-11e8-9165-727c3aca7510.png)

![image](https://user-images.githubusercontent.com/35204357/35292952-fb5f0486-0026-11e8-949c-365340963952.png)

**Comment by austin-berry** [comment]
@Dud10982 Ah, I did notice that in some of my searches. I totally agree. I really like the modded menus. Looks really nice and dynamic as far as inventory items go. So we'll need to add an item category to sort items by (which this helps a lot on assembling the bigger picture of inventory items). I'll get an update worked on and posted.

**Comment by Alcatraz7** [comment]
I do like having the 3d render of the object show up. But I feel like everything is going to be cluttered with a layout like Skyrim. But I think we can make something like the skyui work.

**Comment by JaysonSteelman** [comment]
why not just keep it simple with the grid style interface? i personally
hates the skyrim inventory system, was too easy to lose shit. I like the
wow style.

**Comment by austin-berry** [comment]
How's the WOW style compare?

**Comment by Dud10982** [comment]
An issue I can think of with the WOW style is that we would have to spend a ton of time on the art style and creating specific individual art for each item so that people would be able to instantly recognize first by picture rather than text. So in short the skyrim layout relies on text and maybe small basic icons first to recognize items and then 3d renders and such second, where as WOW relies on recognizable icons to recognize items and then text second.

http://www.wowinterface.com/downloads/cat20.html#
https://www.gamepressure.com/download.asp?ID=45821
