### ISSUE TITLE
Quest System Implementation Testing, Verification, and Modifications

### ISSUE THREAD

**Issue by austin-berry** [EniariGames/StaticShock#3]
We need to go over the Quest System thoroughly and decide whether or not we want to make changes or redesign the system all-together. If not, we need to make sure there are no system bugs or issues.

**Comment by austin-berry** [comment]
How's everything coming along here David? I'm keeping this project phase separate from the #11 Inventory System Widget project task. That I think should be kept separate unless you have any reasons you'd like to keep them together. 

If there's any new ideas or anything, create a new issue item and add the corresponding project to that item. If there's any bugs, issues, or flaws that you've noticed with the current system, respond to this message and we can hash everything out.

If we're all good, feel free to comment and close this issue.

**Comment by Dud10982** [comment]
Since school has started i haven't really had any time to do much. I think that since were still in pretty early stages we can still experiment with the quest system. Until we can get a very basic bland model down, then we can expand on that. I dont really want to throw everything into one idea and then later down the line realize that we cant do something because of limitations and then have to start over. Id rather we hash everything out first and create the most broad system we can that can handle everything we can think of but at its most basic core and then move up from there.

**Comment by austin-berry** [comment]
Perfect, I totally agree. And thanks for the update. I'll ensure to keep it very generic and cover a broader spectrum until we have a more complete idea structure of how we want it to be.

**Comment by austin-berry** [comment]
Tested and verified working with the new 2.0 quest system.
